package info.johnnywinters.taskmaster;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "tasks")
public class Task {
    private String id;
    private String title;
    private String description;
    private String status = "Available";
    private String assignee;

    public Task(){}

    public Task(String title, String description, String status, String assignee){
        this.title = title;
        this.description = description;
        if(assignee != null){
            this.setAssignee(assignee);
        }
    }

    public void incrementStatus(){
        if(this.status.equals("Available")) this.status = "Assigned";
        else if(this.status.equals("Assigned")) this.status = "Accepted";
        else if(this.status.equals("Accepted")) this.status = "Finished";
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBAttribute
    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    @DynamoDBAttribute
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @DynamoDBAttribute
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @DynamoDBAttribute
    public String getAssignee(){
        return this.assignee;
    }

    public void setAssignee(String assignee){
        this.assignee = assignee;
        this.setStatus("Assigned");
    }
}
